// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const create_Refresh_Token = `-- name: Create_Refresh_Token :one
INSERT INTO refresh_tokens (token , user_id, created_at ,updated_at ,expires_at , revoked_at)
VALUES(
    $1,$2,NOW(),NOW(),NOW() + INTERVAL '60 days',NULL
)
RETURNING token, created_at, updated_at, expires_at, revoked_at, user_id
`

type Create_Refresh_TokenParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) Create_Refresh_Token(ctx context.Context, arg Create_Refresh_TokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, create_Refresh_Token, arg.Token, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserID,
	)
	return i, err
}

const getUserFromRefreshToken = `-- name: GetUserFromRefreshToken :one
SELECT token, created_at, updated_at, expires_at, revoked_at, user_id from refresh_tokens 
where token = $1
`

func (q *Queries) GetUserFromRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getUserFromRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserID,
	)
	return i, err
}

const revoke_Refresh_Token = `-- name: Revoke_Refresh_Token :exec
UPDATE refresh_tokens
SET revoked_at = now(),
    updated_at = now()
WHERE token = $1 AND revoked_at IS NULL
`

func (q *Queries) Revoke_Refresh_Token(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revoke_Refresh_Token, token)
	return err
}
